name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and test
        run: |
          docker build -t reactjs-basic .
          docker run reactjs-basic yarn test

      - name: Push image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-basic:${{ github.sha }}

  deploy:
    needs: build_and_test
    runs-on: self-hosted

    steps:
      - name: Deploy to server
        run: |
          cd /build 
          sed -i '5s/.*/    image: "${{ secrets.DOCKERHUB_USERNAME }}\/reactjs-basic:${{ github.sha }}"/' docker-compose.yaml
          sed -i '8s/.*/      - 80:3000/' docker-compose.yaml
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reactjs-basic:${{ github.sha }}
          docker compose down
          docker compose up --build -d